### ISSUE TITLE
0.1.3 failing on macOS 10.14

### ISSUE THREAD

**Issue by cashcass** [greenaddress/WalletElectron#13]
Process:               GreenAddress Wallet [8234]
Path:                  /Applications/GreenAddress Wallet.app/Contents/MacOS/GreenAddress Wallet
Identifier:            com.blockstream.greenaddress-electron
Version:               0.1.3 (0.1.3)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           GreenAddress Wallet [8234]
User ID:               501

Date/Time:             2018-11-06 01:13:52.825 -0800
OS Version:            Mac OS X 10.14 (18A391)
Report Version:        12
Time Awake Since Boot: 420000 seconds
Time Since Wake:       14000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Squirrel.framework/Squirrel
  Referenced from: /Applications/GreenAddress Wallet.app/Contents/MacOS/GreenAddress Wallet
  Reason: image not found

Binary Images:
       0x108a78000 -        0x108a78ff7 +com.blockstream.greenaddress-electron (0.1.3 - 0.1.3) <F8DFE287-C6B4-3716-B3B3-CDF539205B40> /Applications/GreenAddress Wallet.app/Contents/MacOS/GreenAddress Wallet
       0x10b08d000 -        0x10b10b6a7  dyld (625.13) <D6387150-2FB8-3066-868D-72E1B1C43982> /usr/lib/dyld
       0x10b16e000 -        0x10f43bf7f +com.github.electron.framework (0) <47724138-F883-3288-AE68-FE904F392A3B> /Applications/GreenAddress Wallet.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
    0x7fff39bac000 -     0x7fff39bacfff  com.apple.Carbon (158 - 158) <DAF95685-B793-34EB-96EA-3E292A9E3378> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff3d1ee000 -     0x7fff3d2f7ff3  com.apple.Bluetooth (6.0.8 - 6.0.8f6) <6CB8A08E-1154-3333-83CC-2A939AC94562> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fff458a0000 -     0x7fff458a0fff  com.apple.quartzframework (1.5 - 23) <103A742C-50F3-3A4A-B787-FDD35F36B6F1> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff458a1000 -     0x7fff45af7fff  com.apple.QuartzCore (1.11 - 693.16.4.2) <2C9E3279-3F97-3440-B937-E5FE888232E2> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff46345000 -     0x7fff4666bfff  com.apple.security (7.0 - 58286.200.222) <AEB638D9-BFE9-319E-A70B-557ACF41117A> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff466fc000 -     0x7fff4672cffb  com.apple.securityinterface (10.0 - 55109.200.8) <8BDA8A18-C4EB-3267-96AB-0C2F2321866D> /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
    0x7fff4672d000 -     0x7fff46731ff3  com.apple.xpc.ServiceManagement (1.0 - 1) <20DB899D-3BAF-36FD-86A6-F66A82074607> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff469a1000 -     0x7fff469b6ffb  com.apple.StoreKit (1.0 - 1) <3A4D0B33-E43C-3D96-8870-0084DA848A18> /System/Library/Frameworks/StoreKit.framework/Versions/A/StoreKit

**Comment by jgriffiths** [comment]
Hi @cashcass - the fixed release is now available at https://github.com/greenaddress/WalletElectron/releases/tag/v0.1.04, please let us know if you have any issues.
