### ISSUE TITLE
Multiple wallets on one device

### ISSUE THREAD

**Issue by aggieben** [greenaddress/WalletElectron#14]
I had a working Green Address wallet on my Windows desktop (for personal use).  I wanted to also have a wallet for my business, so I logged out of that one, and then created a new wallet for my business.  Now I am unable to log back in to my personal wallet.  Is this a supported scenario?  If not, how do I get back to my personal wallet (which has funds in it)?

**Comment by jgriffiths** [comment]
Hi,

Please contact our support services at info@greenaddress.it for support. The short answer to your query is that you can always log in with your mnemonics, but you can only have one pin active at a time. If you enter your pin incorrectly 3 times you can log in with the other mnemonic and from then forward, do not set up a pin if you plan to switch between the wallets often.
