### ISSUE TITLE
Copy Previous Receiver's Wallet Address

### ISSUE THREAD

**Issue by Megawatt7** [greenaddress/WalletElectron#16]
Hello, on mobile iOS when I click on a previous transaction and view the receiver's wallet address, I can't copy their BTC address. I'm forced to view block explorer and find their address there and copy it.

**Comment by alessandro-saglimbeni** [comment]
Hey @Alesio7 this issue is best placed in https://github.com/Blockstream/green_ios/issues rather then here ;)

Anyway you should be able to copy to clipboard addresses and other transaction details with the new iOS version 3.2.3 released 2 days ago.

Does 3.2.3 solves your issue?

**Comment by jgriffiths** [comment]
Wallet is deprecated in favour of https://blockstream.com/green/, closing
