### ISSUE TITLE
Issue when trying to scan QR

### ISSUE THREAD

**Issue by teseo** [greenaddress/WalletElectron#26]
In the past if I had the laptop closed and no camera was available, it used to prompt a file picker to select my qr file. Now I see this yellow screen and no file picker is available.

![Screenshot 2020-10-09 at 22 38 07](https://user-images.githubusercontent.com/2123048/95633867-7f22a280-0a80-11eb-8859-af1f237f3216.png)

**Comment by jgriffiths** [comment]
Hi @teseo The electron wallet you are using has been replaced by our new Green mobile apps and green_qt for the desktop - so the electron wallet is no longer maintained. Please download Green wallet from https://blockstream.com/green/ - you can log in using your existing mnemonic.

If you have any difficulties with the Green please reach out to info@greenaddress.it and our support staff wil take a look, thanks.
